// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts(id, user_id)
VALUES($1, $2)
RETURNING id, user_id, balance, created_at, updated_at
`

type CreateAccountParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions(id, user_id, from_account_id, to_account_id, amount, status)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, from_account_id, to_account_id, amount, status, created_at, updated_at
`

type CreateTransactionParams struct {
	ID            pgtype.UUID       `json:"id"`
	UserID        pgtype.UUID       `json:"user_id"`
	FromAccountID pgtype.UUID       `json:"from_account_id"`
	ToAccountID   pgtype.UUID       `json:"to_account_id"`
	Amount        pgtype.Numeric    `json:"amount"`
	Status        TransactionStatus `json:"status"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, cpf, name, password) 
VALUES($1, $2, $3, $4)
RETURNING id, cpf, name, password, created_at, updated_at
`

type CreateUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Cpf      string      `json:"cpf"`
	Name     string      `json:"name"`
	Password string      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Cpf,
		arg.Name,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cpf,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByCPF = `-- name: FindUserByCPF :one
SELECT id, cpf, name, password, created_at, updated_at
FROM users
WHERE cpf = $1
`

func (q *Queries) FindUserByCPF(ctx context.Context, cpf string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByCPF, cpf)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Cpf,
		&i.Name,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, balance, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, from_account_id, to_account_id, amount, status, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT id, user_id, from_account_id, to_account_id, amount, status, created_at, updated_at
FROM transactions
WHERE user_id = $1
LIMIT $2 OFFSET $3
`

type GetUserTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetUserTransactions(ctx context.Context, arg GetUserTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUserTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccounts = `-- name: ListUserAccounts :many
SELECT id, user_id, balance, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserAccountsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUserAccounts(ctx context.Context, arg ListUserAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listUserAccounts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE accounts
SET balance = $2, updated_at = now() 
WHERE id = $1
RETURNING id, user_id, balance, created_at, updated_at
`

type UpdateBalanceParams struct {
	ID      pgtype.UUID    `json:"id"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionsStatus = `-- name: UpdateTransactionsStatus :one
UPDATE transactions
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, from_account_id, to_account_id, amount, status, created_at, updated_at
`

type UpdateTransactionsStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status TransactionStatus `json:"status"`
}

func (q *Queries) UpdateTransactionsStatus(ctx context.Context, arg UpdateTransactionsStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionsStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
