// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindUserByCPF(ctx context.Context, cpf string) (User, error)
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error)
	GetUserTransactions(ctx context.Context, arg GetUserTransactionsParams) ([]Transaction, error)
	ListUserAccounts(ctx context.Context, arg ListUserAccountsParams) ([]Account, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error)
	UpdateTransactionsStatus(ctx context.Context, arg UpdateTransactionsStatusParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
